CREATE DATABASE TOY_STORE;

USE TOY_STORE;

SELECT * FROM INVENTORY;
SELECT * FROM PRODUCTS;
SELECT * FROM SALES;
SELECT * FROM STORES;


--LETS START--

--Sales Trend Analysis
--1. Monthly Wise Sales Trend Over the Stores, Location for Both Year (2022 & 2023)--

CREATE VIEW MONTHLY_SALES_OVER_STORES AS

SELECT YEAR(S.DATE) AS SALES_YEAR, MONTH(S.DATE) AS SALES_MONTH, 
	ST.STORE_ID, ST.STORE_NAME, ST.STORE_CITY, ST.STORE_LOCATION,
	SUM(S.UNITS) AS TOTAL_UNITS, SUM(S.UNITS*P.PRODUCT_RETAIL_PRICE) AS TOTAL_SALES_AMOUNT
FROM SALES S
JOIN STORES ST ON S.STORE_ID = ST.STORE_ID
JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
WHERE YEAR(S.DATE) IN (2022, 2023)
GROUP BY YEAR(S.DATE), MONTH(S.DATE),
	ST.STORE_ID, ST.STORE_NAME, ST.STORE_CITY, ST.STORE_LOCATION
ORDER BY SALES_YEAR, SALES_MONTH, ST.STORE_ID
OFFSET 0 ROWS;


--FINAL ANSWER--

SELECT * FROM MONTHLY_SALES_OVER_STORES;

--Stores Performance Analysis-
--2. Find the Sales Trend Over the Different Stores and Find the Best and Least Five Stores as Per the Performance--

CREATE VIEW Sales_Trend_Over_the_Different_Stores AS

SELECT ST.STORE_ID, ST.STORE_NAME, ST.STORE_CITY, ST.STORE_LOCATION,
	SUM(S.UNITS) AS TOTAL_UNITS, SUM(S.UNITS*P.PRODUCT_RETAIL_PRICE) AS TOTAL_SALES_AMOUNT
FROM SALES S
JOIN STORES ST ON S.STORE_ID = ST.STORE_ID
JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY ST.STORE_ID, ST.Store_Name, ST.STORE_CITY, ST.STORE_LOCATION
ORDER BY TOTAL_SALES_AMOUNT DESC
OFFSET 0 ROWS;

--FINAL ANSWER--

SELECT * FROM Sales_Trend_Over_the_Different_Stores;


--3. Best 5 and Worst 5 Stores--


CREATE VIEW BEST_AND_WORST_5_STORES AS

SELECT * FROM (
    SELECT TOP 5 ST.STORE_ID, ST.STORE_NAME, ST.STORE_CITY, ST.STORE_LOCATION,
	    SUM(S.UNITS) AS TOTAL_UNITS, SUM(S.UNITS*P.PRODUCT_RETAIL_PRICE) AS TOTAL_SALES_AMOUNT, 'TOP' AS RANKGROUP
    FROM SALES S
    JOIN STORES ST ON S.STORE_ID = ST.STORE_ID
    JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY ST.STORE_ID, ST.Store_Name, ST.STORE_CITY, ST.STORE_LOCATION
    ORDER BY TOTAL_SALES_AMOUNT DESC

    UNION ALL

    SELECT TOP 5 ST.STORE_ID, ST.STORE_NAME, ST.STORE_CITY, ST.STORE_LOCATION,
	    SUM(S.UNITS) AS TOTAL_UNITS, SUM(S.UNITS*P.PRODUCT_RETAIL_PRICE) AS TOTAL_SALES_AMOUNT, 'BOTTOM' AS RANKGROUP
    FROM SALES S
    JOIN STORES ST ON S.STORE_ID = ST.STORE_ID
    JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
    GROUP BY ST.STORE_ID, ST.Store_Name, ST.STORE_CITY, ST.STORE_LOCATION
    ORDER BY TOTAL_SALES_AMOUNT ASC) AS FINAL

ORDER BY RANKGROUP DESC, TOTAL_SALES_AMOUNT DESC
OFFSET 0 ROWS;

--FINAL ANSWER--

SELECT * FROM BEST_AND_WORST_5_STORES;


--4. Does Store Area/location Affect Sales? (Aggregate by Store_location)--

CREATE VIEW SALES_AFFECT_BY_LOCATION AS

SELECT 
    ST.STORE_LOCATION, COUNT(DISTINCT ST.STORE_ID) AS NUM_STORES,
    SUM(S.UNITS) AS TOTAL_UNITS, SUM(S.UNITS*P.PRODUCT_RETAIL_PRICE) AS TOTAL_SALES_AMOUNT,
    AVG(S.UNITS*P.PRODUCT_RETAIL_PRICE) AS AVG_SALE_AMOUNT_PER_TRANSACTION
FROM SALES S
JOIN STORES ST ON S.STORE_ID = ST.STORE_ID
JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY ST.STORE_LOCATION
ORDER BY TOTAL_SALES_AMOUNT DESC
OFFSET 0 ROWS;


--FINAL ASNWER--

SELECT * FROM SALES_AFFECT_BY_LOCATION;


--5. Product vs Store Relationship — Product Performance Per Store--

CREATE VIEW PRODUCT_VS_STORES AS

SELECT 
    ST.STORE_ID, ST.STORE_NAME, P.PRODUCT_ID, P.PRODUCT_NAME, P.PRODUCT_CATEGORY,
    SUM(S.UNITS) AS TOTAL_UNITS, SUM(S.UNITS*P.PRODUCT_RETAIL_PRICE) AS TOTAL_SALES_AMOUNT
FROM SALES S
JOIN STORES ST ON S.STORE_ID = ST.STORE_ID
JOIN PRODUCTS P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY ST.STORE_ID, ST.STORE_NAME, P.PRODUCT_ID, P.PRODUCT_NAME, P.PRODUCT_CATEGORY
ORDER BY ST.STORE_ID, TOTAL_SALES_AMOUNT DESC
OFFSET 0 ROWS;


--FINAL ANSWER--

SELECT * FROM PRODUCT_VS_STORES;


--6. Which Product Category Outshines the Rest (by Sales Amount)--

CREATE VIEW BEST_PRODUCT_CATEGORY AS

SELECT
    P.PRODUCT_CATEGORY,
    SUM(S.UNITS) AS TOTAL_UNITS, SUM(S.UNITS*P.PRODUCT_RETAIL_PRICE) AS TOTAL_SALES_AMOUNT
FROM SALES S
JOIN PRODUCTS P ON S.Product_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_CATEGORY
ORDER BY TOTAL_SALES_AMOUNT DESC
OFFSET 0 ROWS;


--FINAL ANSWER--

SELECT * FROM BEST_PRODUCT_CATEGORY;


--7. Highest-demand Product Across All Locations (by Units Sold)--


CREATE VIEW HIGHEST_DEMAND_PRODUCT AS

SELECT TOP 1
    P.PRODUCT_ID, P.PRODUCT_NAME, P.PRODUCT_CATEGORY,
    SUM(S.UNITS) AS TOTAL_UNITS_SOLD, SUM(S.UNITS*P.PRODUCT_RETAIL_PRICE) AS TOTAL_SALES_AMOUNT
FROM SALES S
JOIN PRODUCTS P ON S.Product_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME, P.PRODUCT_CATEGORY
ORDER BY TOTAL_UNITS_SOLD DESC;


--FINAL ASNWER--

SELECT * FROM HIGHEST_DEMAND_PRODUCT;


--8) Inventory Health — Average Inventory Per Store & Per Product (and Simple Turnover)--

CREATE VIEW INVENTORY_HEALTH AS

SELECT
    I.STORE_ID, ST.STORE_NAME, I.PRODUCT_ID, P.PRODUCT_NAME, 
    AVG(I.STOCK_ON_HAND) AS AVG_STOCK_ON_HAND,
    SUM(S.UNITS) AS TOTAL_UNITS_SOLD,
    CASE
        WHEN AVG(I.STOCK_ON_HAND) > 0 THEN
            SUM(S.UNITS) / AVG(I.STOCK_ON_HAND)
        ELSE
            NULL
    END AS INVENTORY_TURNOVER_RATIO
FROM INVENTORY I
JOIN STORES ST ON I.STORE_ID = ST.STORE_ID
JOIN PRODUCTS P ON I.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN SALES S ON S.STORE_ID = I.STORE_ID AND S.PRODUCT_ID = I.PRODUCT_ID AND YEAR(S.DATE) = 2023
GROUP BY I.STORE_ID, ST.STORE_NAME, I.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY INVENTORY_TURNOVER_RATIO DESC
OFFSET 0 ROWS;

--FINAL ANSWER--

SELECT * FROM INVENTORY_HEALTH;